# Generated by Django 4.0.6 on 2023-01-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="name",
            field=models.CharField(default="Event Name", max_length=250),
            preserve_default=False,
        ),
    ]
