# Generated by Django 4.0.6 on 2023-01-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_event_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="total_seating_rows",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="total_service_count",
            field=models.PositiveIntegerField(),
        ),
    ]
