# Generated by Django 4.0.6 on 2023-02-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0003_alter_event_total_seating_rows_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="double_counting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="other_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                choices=[
                    ("Sunday", "Sunday"),
                    ("Wednesday", "Wednesday"),
                    ("Communion Service", "Communion Service"),
                    ("Other", "Other"),
                ],
                default="Sunday",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="total_service_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
