# Generated by Django 4.0.6 on 2023-02-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0004_event_double_counting_event_other_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="message",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="minister",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
