# Generated by Django 4.0.6 on 2023-05-04 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_event_message_event_minister'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='message',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Message Title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='other_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Other Details'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_service_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Service No'),
        ),
    ]
