# Generated by Django 4.0.6 on 2023-01-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0003_alter_attendance_allocated_row_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="counting_done",
            field=models.BooleanField(default=False),
        ),
    ]
