# Generated by Django 4.0.6 on 2023-02-20 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0004_attendance_counting_done"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="children_count",
            new_name="adult_coverts_count",
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="coverts_count",
            new_name="adult_female_count",
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="female_count",
            new_name="adult_male_count",
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="first_timer_count",
            new_name="children_teenager_female_count",
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="male_count",
            new_name="children_teenager_male_count",
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="teenager_count",
            new_name="female_first_timer_count",
        ),
        migrations.AddField(
            model_name="attendance",
            name="male_first_timer_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendance",
            name="teenage_coverts_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendance",
            name="teenager_female_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendance",
            name="teenager_male_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="count_coordinator",
            field=models.ForeignKey(
                limit_choices_to={"is_staff": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="count_coordinator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
