# Generated by Django 4.0.6 on 2023-02-20 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "attendance",
            "0005_rename_children_count_attendance_adult_coverts_count_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="children_teenager_female_count",
            new_name="children_female_count",
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="children_teenager_male_count",
            new_name="children_male_count",
        ),
    ]
