# Generated by Django 4.0.6 on 2023-02-20 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "attendance",
            "0006_rename_children_teenager_female_count_attendance_children_female_count_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="teenage_coverts_count",
            new_name="teenager_coverts_count",
        ),
    ]
