# Generated by Django 4.0.6 on 2023-02-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0007_rename_teenage_coverts_count_attendance_teenager_coverts_count",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="counting_index",
            field=models.CharField(
                choices=[
                    ("FIRST_COUNTING", "FIRST_COUNTING"),
                    ("SECOND_COUNTING", "SECOND_COUNTING"),
                ],
                default="FIRST_COUNTING",
                max_length=250,
            ),
        ),
    ]
