# Generated by Django 4.0.6 on 2023-05-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_counting_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='service_index',
            field=models.PositiveIntegerField(verbose_name='Service No'),
        ),
    ]
