# Generated by Django 4.0.6 on 2023-01-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_customuser_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Male",
                max_length=6,
            ),
            preserve_default=False,
        ),
    ]
